# Copyright VMware, Inc.
# SPDX-License-Identifier: APACHE-2.0

version: '2'

services:
  mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: ahmad989
      MONGO_INITDB_ROOT_PASSWORD: password
    ports:
      - 27017:27017

  mongo-express:    
    image: mongo-express
    restart: always
    # ports:
    #   - 8081:8085
    # environment:
    #   ME_CONFIG_MONGODB_ADMINUSERNAME: root
    #   ME_CONFIG_MONGODB_ADMINPASSWORD: example
    #   ME_CONFIG_MONGODB_URL: mongodb://root:example@mongo:27017/
  myapp:
    image: docker.io/bitnami/laravel:10
    ports:
      - '8000:8000'
    environment:
      - DB_HOST=mongodb
      - DB_PORT=27017
      - DB_USERNAME=
      - DB_DATABASE=elevatus
    volumes:
      - './my-project:/app'
    depends_on:
      - mongo
  config:
    build: 
      context: .
      dockerfile: Dockerfile
